url=http://gbair.net/gobudgetairdemo1.0/flights
testurl=https://www.saucedemo.com/
browser=chrome
Sector=MAA,DXB,10-Feb-2025,18-Feb-2025
BookNow=Book Now
implicitlyWait=10
username=standard_user
password=secret_sauce
packagename=Sauce Labs Onesie,Sauce Labs Bike Light
firstname=lksaas
lastname=asdas
zipcode=8292

